---
inventory:
    plugin: SimpleInventory
    options:
        host_file: "hosts.yaml"
        group_oule: "groups.yaml"
        defaults_file: "defaults.yaml"
runner:
    plugin: threaded
    options:
        num_workers: 100
